[2024-11-15T13:36:48.010+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-15T13:36:48.022+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow_clima_1.get_weather_data manual__2024-11-15T13:36:35.887187+00:00 [queued]>
[2024-11-15T13:36:48.246+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow_clima_1.get_weather_data manual__2024-11-15T13:36:35.887187+00:00 [queued]>
[2024-11-15T13:36:48.330+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-11-15T13:36:48.354+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): get_weather_data> on 2024-11-15 13:36:35.887187+00:00
[2024-11-15T13:36:48.470+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=849) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-15T13:36:48.472+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '***_clima_1', 'get_weather_data', 'manual__2024-11-15T13:36:35.887187+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/***_clima_1.py', '--cfg-path', '/tmp/tmpdr4mmj1s']
[2024-11-15T13:36:48.553+0000] {standard_task_runner.py:72} INFO - Started process 858 to run task
[2024-11-15T13:36:48.554+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask get_weather_data
[2024-11-15T13:36:48.596+0000] {task_command.py:467} INFO - Running <TaskInstance: airflow_clima_1.get_weather_data manual__2024-11-15T13:36:35.887187+00:00 [running]> on host 0fb026160db8
[2024-11-15T13:36:48.662+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***_clima_1' AIRFLOW_CTX_TASK_ID='get_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-15T13:36:35.887187+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-15T13:36:35.887187+00:00'
[2024-11-15T13:36:48.663+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-15T13:36:48.664+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-15T13:36:48.665+0000] {logging_mixin.py:190} INFO - Current task name:get_weather_data state:running start_date:2024-11-15 13:36:48.233721+00:00
[2024-11-15T13:36:48.665+0000] {logging_mixin.py:190} INFO - Dag name:***_clima_1 and current dag run status:running
[2024-11-15T13:36:48.666+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-15T13:36:48.676+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_clima_1.py", line 33, in extract_data
    s3 = boto3.client (
         ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/boto3/__init__.py", line 92, in client
    return _get_default_session().client(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Session.client() got an unexpected keyword argument 'endpoint_uf'
[2024-11-15T13:36:48.977+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-15T13:36:48.978+0000] {logging_mixin.py:190} INFO - Task start:2024-11-15 13:36:48.233721+00:00 end:2024-11-15 13:36:48.976297+00:00 duration:0.742576
[2024-11-15T13:36:48.979+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): get_weather_data> dag:<DAG: ***_clima_1> dagrun:<DagRun ***_clima_1 @ 2024-11-15 13:36:35.887187+00:00: manual__2024-11-15T13:36:35.887187+00:00, state:running, queued_at: 2024-11-15 13:36:35.900702+00:00. externally triggered: True>
[2024-11-15T13:36:49.080+0000] {logging_mixin.py:190} INFO - Failure caused by Session.client() got an unexpected keyword argument 'endpoint_uf'
[2024-11-15T13:36:49.124+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=***_clima_1, task_id=get_weather_data, run_id=manual__2024-11-15T13:36:35.887187+00:00, execution_date=20241115T133635, start_date=20241115T133648, end_date=20241115T133648
[2024-11-15T13:36:49.260+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-15T13:36:49.357+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 14 for task get_weather_data (Session.client() got an unexpected keyword argument 'endpoint_uf'; 858)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_clima_1.py", line 33, in extract_data
    s3 = boto3.client (
         ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/boto3/__init__.py", line 92, in client
    return _get_default_session().client(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Session.client() got an unexpected keyword argument 'endpoint_uf'
[2024-11-15T13:36:49.694+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-15T13:36:49.709+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-15T13:36:49.712+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
